### ISSUE TITLE
Ability to search for potential IAM users from a name 

### ISSUE THREAD

**Issue by mchv** [guardian/security-hq#111]
When someone leave we have to delete all IAM users the person may have created in our various AWS accounts. Thanks to `janus` we have far less of them and with the current [iam view](https://security-hq.gutools.co.uk/iam) I can inspect all accounts to find potential IAM credentials.

However it will be great to have a small feature to quickly highlight them from a given name.

Taking as an example `john doe`, patterns to look for could be:

- `jd`
- `jdoe` 
- `jdoe-*` 
-  `johndoe`
- `john.doe`

**Comment by adamnfish** [comment]
great idea :+1:

**Comment by akash1810** [comment]
With https://github.com/guardian/service-catalogue, we can answer this via [Grafana](https://metrics.gutools.co.uk/d/qsF650yVk/aws-iam-users?orgId=1).

Closing.
